packages:
  - 'shared/packages/*'
  - 'apps/*'
allowBuilds:
  '@prisma/engines': true
  argon2: set this to true or false
  bcrypt: true
  esbuild: true
  prisma: true
  sharp: true
  unrs-resolver: true
